USE [cms]
GO
SET IDENTITY_INSERT [CMSWEB].[CODE_VALUE_T] ON 

GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(3 AS Numeric(18, 0)), N'FL', N'STUDENT_TYPE                                      ', N'Full Time ', N'Full Time ', NULL, NULL, CAST(N'2016-10-04 13:28:33.270' AS DateTime), N'ADMIN     ', CAST(N'2016-10-04 13:28:33.270' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(4 AS Numeric(18, 0)), N'PT', N'STUDENT_TYPE                                      ', N'Part Time ', N'Part Time ', NULL, NULL, CAST(N'2016-10-04 13:32:57.553' AS DateTime), N'ADMIN     ', CAST(N'2016-10-04 13:32:57.553' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(5 AS Numeric(18, 0)), N'CELL                                              ', N'TELEPHONE_TYPE                                    ', N'Cell      ', N'Cell Phone', NULL, NULL, CAST(N'2016-10-07 21:38:58.563' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:38:58.563' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(6 AS Numeric(18, 0)), N'HOME                                              ', N'TELEPHONE_TYPE                                    ', N'Home      ', N'Home Phone', NULL, NULL, CAST(N'2016-10-07 21:49:14.947' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:49:14.947' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(7 AS Numeric(18, 0)), N'WORK                                              ', N'TELEPHONE_TYPE                                    ', N'Work      ', N'Work Phone', NULL, NULL, CAST(N'2016-10-07 21:49:36.063' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:49:36.063' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(8 AS Numeric(18, 0)), N'HOME                                              ', N'ADDRESS_TYPE                                      ', N'Home      ', N'Home      ', NULL, NULL, CAST(N'2016-10-07 21:50:08.413' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:50:08.413' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(9 AS Numeric(18, 0)), N'WORK                                              ', N'ADDRESS_TYPE                                      ', N'Work      ', N'Work      ', NULL, NULL, CAST(N'2016-10-07 21:50:40.800' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:50:40.800' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(10 AS Numeric(18, 0)), N'OTHER                                             ', N'ADDRESS_TYPE                                      ', N'Other     ', N'Other     ', NULL, NULL, CAST(N'2016-10-07 21:51:11.133' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:51:11.133' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(11 AS Numeric(18, 0)), N'FALL                                              ', N'SEMESTER                                          ', N'Fall      ', N'Fall      ', NULL, NULL, CAST(N'2016-10-07 21:53:02.683' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:53:02.683' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(12 AS Numeric(18, 0)), N'SPRING                                            ', N'SEMESTER                                          ', N'Spring    ', N'Spring    ', NULL, NULL, CAST(N'2016-10-07 21:53:20.753' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:53:20.753' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(13 AS Numeric(18, 0)), N'SUMMER                                            ', N'SEMESTER                                          ', N'Summer    ', N'Summer    ', NULL, NULL, CAST(N'2016-10-07 21:53:52.867' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:53:52.867' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(14 AS Numeric(18, 0)), N'A ', N'GRADE                                             ', N'A Grade   ', N'A Grade   ', NULL, NULL, CAST(N'2016-10-07 21:56:53.903' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:56:53.903' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(15 AS Numeric(18, 0)), N'A-', N'GRADE                                             ', N'A- Grade  ', N'A- Grade  ', NULL, NULL, CAST(N'2016-10-07 21:57:16.520' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:57:16.520' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(16 AS Numeric(18, 0)), N'A+', N'GRADE                                             ', N'A+ Grade  ', N'A+ Grade  ', NULL, NULL, CAST(N'2016-10-07 21:57:42.050' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:57:42.050' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(17 AS Numeric(18, 0)), N'B ', N'GRADE                                             ', N'B Grade   ', N'B Grade   ', NULL, NULL, CAST(N'2016-10-07 21:58:23.253' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:58:23.253' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(18 AS Numeric(18, 0)), N'B-', N'GRADE                                             ', N'B- Grade  ', N'B- Grade  ', NULL, NULL, CAST(N'2016-10-07 21:58:49.380' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:58:49.380' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(19 AS Numeric(18, 0)), N'B+', N'GRADE                                             ', N'B+ Grade  ', N'B+ Grade  ', NULL, NULL, CAST(N'2016-10-07 21:59:29.903' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 21:59:29.903' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(20 AS Numeric(18, 0)), N'C ', N'GRADE                                             ', N'C Grade   ', N'C Grade   ', NULL, NULL, CAST(N'2016-10-07 22:00:30.200' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 22:00:30.200' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(21 AS Numeric(18, 0)), N'D ', N'GRADE                                             ', N'D Grade   ', N'D Grade   ', NULL, NULL, CAST(N'2016-10-07 22:02:06.040' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 22:02:06.040' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(22 AS Numeric(18, 0)), N'F ', N'GRADE                                             ', N'Fail      ', N'Fail      ', NULL, NULL, CAST(N'2016-10-07 22:02:26.500' AS DateTime), N'ADMIN     ', CAST(N'2016-10-07 22:02:26.500' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(23 AS Numeric(18, 0)), N'asdf                                              ', N'adsf                                              ', N'          ', N'          ', NULL, NULL, CAST(N'2016-10-08 15:59:18.027' AS DateTime), N'ADMIN     ', CAST(N'2016-10-08 15:59:18.027' AS DateTime), N'ADMIN                                               ')
GO
INSERT [CMSWEB].[CODE_VALUE_T] ([OBJECTID], [CODE], [CODE_GROUP], [SHORT_DESCRIPTION], [LONG_DESCRIPTION], [EFFECTIVE_DATETIME], [EFFECTIVE_THRU_DATETIME], [ROW_CREATED_DATETIME], [ROW_CREATED_BY], [ROW_LAST_CHANGED_DATETIME], [ROW_LAST_CHANGED_BY]) VALUES (CAST(25 AS Numeric(18, 0)), N'adf                                               ', N'sdfadsf                                           ', N'          ', N'          ', NULL, NULL, CAST(N'2016-10-08 16:07:54.817' AS DateTime), N'ADMIN     ', CAST(N'2016-10-08 16:07:54.817' AS DateTime), N'ADMIN                                               ')
GO
SET IDENTITY_INSERT [CMSWEB].[CODE_VALUE_T] OFF
GO
